service: my-app

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:us-east-1:551342549342:table/todos"
functions:
  helloWorld:
    handler: handler.run

  httpHello:
    handler: httpHandler.run
    events:
      - http:
          path: /http
          method: get
  getTodo:
    handler: get.run
    events:
      - http:
          path: todos/{id}
          method: get
  createTodo:
    handler: createHandler.run
    events:
      - http:
          path: /http
          method: post
resources:
  Resources:
    TodosTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: todos
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          - 
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

